openapi: 3.0.0
info:
  title: User Authentication & Personalization API
  version: 1.0.0
paths:
  /auth/signup:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - software_background
                - hardware_background
              properties:
                email:
                  type: string
                  format: email
                  description: User's email address.
                password:
                  type: string
                  format: password
                  description: User's chosen password.
                software_background:
                  type: array
                  items:
                    type: string
                  description: User's software background (e.g., Python, ROS 2).
                hardware_background:
                  type: array
                  items:
                    type: string
                  description: User's hardware background (e.g., NVIDIA Jetson).
      responses:
        '200':
          description: User registered successfully.
  /auth/signin:
    post:
      summary: Authenticate and log in a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  description: User's email address.
                password:
                  type: string
                  format: password
                  description: User's password.
      responses:
        '200':
          description: User logged in successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                  token_type:
                    type: string
  /user/preferences:
    post:
      summary: Update user personalization preferences
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                difficulty:
                  type: string
                  enum: [beginner, intermediate, advanced]
                focus_area:
                  type: string
      responses:
        '200':
          description: Preferences updated.
  /user/chapters/{chapter_id}/personalize:
    get:
      summary: Get personalized chapter content
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: chapter_id
          required: true
          schema:
            type: string
          description: The ID of the chapter.
      responses:
        '200':
          description: Personalized chapter content.
          content:
            text/markdown:
              schema:
                type: string
  /user/chapters/{chapter_id}/translate/urdu:
    get:
      summary: Get Urdu translated chapter content
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: chapter_id
          required: true
          schema:
            type: string
          description: The ID of the chapter.
      responses:
        '200':
          description: Urdu translated chapter content.
          content:
            text/markdown:
              schema:
                type: string
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
